blank_issues_enabled: false
issue_templates:
  - name: Feature Template
    description: Suggest an feature for this project ğŸ‘©â€ğŸ’»
    file: feature.md
  - name: Bug Report Template
    description: If something doesn't work ğŸ”§
    file: bug_report.md
  - name: Experiment Template
    description: Suggest an experiment for this project ğŸ§‘ğŸ»â€ğŸ”¬
    file: experiment.md
  - name: Research Template
    description: Suggest an research to generate ideas ğŸ‘¨â€ğŸ«
    file: research.md
